name: Release u-boot mainline with custom bootorder
run-name: ${{ inputs.bootorder}} ${{ inputs.bootorder_custom}}
on:
  workflow_dispatch:
    inputs:      
      uboot_repo:
        required: true
        type: choice
        description: u-boot git repo
        options: 
        - https://source.denx.de/u-boot/u-boot
        - custom_repo
      uboot_repo_custom:
        description: custom u-boot git repo
        required: false
        type: string
      uboot_ref:
        required: true
        type: choice
        description: u-boot ref
        options: 
        - v2024.01
        - v2023.10
        - master
        - custom_ref
      uboot_ref_custom:
        description: custom u-boot ref
        required: false
        type: string


jobs:
  build:
    name: ${{ inputs.uboot_ref }}-${{ matrix.boards.name }}-${{ matrix.boards.bootorder }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: 
          [
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "bootorder",
              "bootorder": "dhcp",
            },
            {
             "name": "rk3588s-orangepi-5",
             "config": "orangepi-5-rk3588s_defconfig",
             "build": "bootorder",
             "bootorder": "dhcp",
            },
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "bootorder",
              "bootorder": "dhcp_pxe",
            },
            {
             "name": "rk3588s-orangepi-5",
             "config": "orangepi-5-rk3588s_defconfig",
             "build": "bootorder",
             "bootorder": "dhcp_pxe",
            },
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "bootorder",
              "bootorder": "dhcp_pxe_emmc",
            },
            {
             "name": "rk3588s-orangepi-5",
             "config": "orangepi-5-rk3588s_defconfig",
             "build": "bootorder",
             "bootorder": "dhcp_pxe_emmc",
            },
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "bootorder",
              "bootorder": "dhcp_pxe_emmc_nvme_sata",
            },
            {
             "name": "rk3588s-orangepi-5",
             "config": "orangepi-5-rk3588s_defconfig",
             "build": "bootorder",
             "bootorder": "dhcp_pxe_emmc_nvme_sata",
            },
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "bootorder",
              "bootorder": "dhcp_pxe_emmc_nvme_sata_usb_sd",
            },
            {
             "name": "rk3588s-orangepi-5",
             "config": "orangepi-5-rk3588s_defconfig",
             "build": "bootorder",
             "bootorder": "dhcp_pxe_emmc_nvme_sata_usb_sd",
            },
          ]

    steps:
      - name: Checkout Opi5-u-boot-custom
        uses: actions/checkout@v3
        with:
          repository: ArchemedIan/Opi5-u-boot-custom
          ref: main
          path: .

      - name: Build "${{ matrix.boards.config }}." variant "${{ matrix.boards.build }}"
        run: |
          cd ${{ matrix.boards.build }}
          chmod a+x ./build.sh 
          ./build.sh "${{ inputs.uboot_ref }}" "${{ inputs.uboot_repo }}" "${{ matrix.boards.config }}" "${{ matrix.boards.bootorder }}" "${{ inputs.uboot_ref_custom }}" "${{ inputs.uboot_repo_custom}}" "${{ inputs.bootorder_custom }}" "${{ matrix.boards.name }}"

      - name: make draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release list | grep "${{ inputs.uboot_ref }}-bootorder" || gh release create --draft "${{ inputs.uboot_ref }}-bootorder"

      - name: make draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release list | grep "${{ inputs.uboot_ref }}-bootorder-spi" || gh release create --draft "${{ inputs.uboot_ref }}-bootorder-spi"

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ inputs.uboot_ref }}-bootorder" ${{ matrix.boards.build }}/out/u-boot-${{ inputs.uboot_ref }}-${{ matrix.boards.name }}__*.bin

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ inputs.uboot_ref }}-bootorder-spi" ${{ matrix.boards.build }}/out/u-boot-${{ inputs.uboot_ref }}-${{ matrix.boards.name }}__*.bin
        
