name: Build u-boot mainline
run-name: Build u-boot mainline
on:
  workflow_dispatch:
    inputs:
      uboot_gh_repo:
        description: u-boot git repo
        required: true
        default: https://source.denx.de/u-boot/u-boot
        type: string
      uboot_ref:
        description: u-boot ref
        required: true
        default: v2024.01-rc4
        type: string

jobs:
  build:
    name: ${{ matrix.boards.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards: 
          [
            {
              "name": "rk3588-orangepi-5-plus",
              "config": "orangepi-5-plus-rk3588_defconfig",
              "build": "mainline",
            }
          ]

    steps:
      - name: Checkout Opi5-u-boot-custom
        uses: actions/checkout@v3
        with:
          repository: ArchemedIan/Opi5-u-boot-custom
          ref: main
          path: .

      - name: Build "${{ inputs.uboot_ref }}" from "${{ inputs.uboot_gh_repo }}" for "${{ matrix.boards.config }}." variant "${{ matrix.boards.build }}"
        run: |
          cd ${{ matrix.boards.build }}
          chmod a+x ./build.sh 
          ./build.sh "${{ inputs.uboot_ref }}" "${{ inputs.uboot_gh_repo }}" "${{ matrix.boards.config }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: u-boot-${{ matrix.boards.name }}
          path: |
            u-boot/u-boot*
            u-boot/idbloader.img
            u-boot/idbloader-spi.img
